### ISSUE TITLE
Environment support for AML pplatform

### ISSUE THREAD

**Issue by konabuta** [konabuta/nni#2]
**What would you like to be added**:
Azure ML Environment support for Azure ML Platform Job.

**Why is this needed**:
Azure ML usually use Environment for Training and Inferencing.

**Without this feature, how does current nni work**：
Only Docker Image

**Components that may involve changes**:
need investigation

**Brief description of your proposal if any**:

**Comment by konabuta** [comment]
Currently we write YAML using docker_image information. We should add support Environment name in YAML.
```yml
trainingService:
  platform: aml
  dockerImage: msranni/nni
  subscriptionId: 82a5d8d3-5322-4c49-b9d6-da6e00be5d57
  resourceGroup: azureml-automl
  workspaceName: azureml-automl
  computeTarget: gpuclusters
  docker_image: msranni/nni:v2.4
```
